# title = "instrument config"

[tsi]
abbrev = "TSI"
name = "Total sky imager"
description = ""
manufacturer = ""
path_level0_fix = "/data/level0/all_sky_imager/oceanet_powershot/"
path_filenames_level0 = "date.strftime('%Y/%Y-%m-%d') + '/*.JPG'"
path_level1a = ""


[hatpro]
abbrev = "HATPRO"
name = "Humidity And Temperature PROfiler"
description = "Mircowave Radiometer"
manufacturer = '''
RPG-Radiometer Physics GmbH
Werner-von-Siemens-Str. 4
53340 Meckenheim
Germany
'''
path_level0_fix = "/data/level0/hatpro/hatpro_oceanet_g1"
path_filenames_level0 = ""
path_level1a = ""


[dummy]
abbrev = "DUMMY"
name = "DUUUUMY"
description = "Mircowave Radiometer"
manufacturer = '''
unknown
'''
path_level0_fix = "/data/level0/"
path_filenames_level0 = ""
path_level1a = ""
